### PR TITLE
Fixing some issues and some new functionalities

### PR DESCRIPTION
**Pull request by DanGeffroy**
result is like : 'EzChat' -> '(3) EzChat'

### CODE REVIEW

**Comment by DanGeffroy** [comment]
added auto scroll :heart: 
this should fix issue #14

**Comment by DanGeffroy** [comment]
added css to emoji autocompleter :heart: 
this should fix #15

**Comment by DanGeffroy** [comment]
added a "new messages" separator

**Comment by DanGeffroy** [comment]
added toast when user try to send empty messages/  empty username

**Comment by skullmasher** [comment]
🥇

**Pull request merged**
